### PR TITLE
RFC: Core Hierarchy

### PR DESCRIPTION
**Pull request by CaptainHayashi**
[Rendered](https://github.com/UniversityRadioYork/bifrost-rfcs/blob/mw-core/resource-hierarchy/core.md)

This is basically how it is in trackd at the moment, as a starting point.

For me, the big question is whether we should (re-?)split `/control/state` into separate states for the different resource hierarchies.  For example, while `/control/state` would be server state (ie quitting, running), `/player/state` would be playing/stopped/paused.  I think this might be a more sane way of doing things, because otherwise the state machine changes from server to server in unpredictable ways, and it means that `playd` and `listd` share a state machine in awkward ways.

### CODE REVIEW

**Comment by LordAro** [comment]
Looks good. I agree wrt /player/state split. Not sure what /control/state/{allowed,current} are doing or why they're necessary

**Comment by CaptainHayashi** [comment]
@LordAro making the set of allowed states discoverable for the client.  This was mainly useful when we had `/player/state` merged in (because different servers would have different states); now it's less so, but I'd probably keep it for consistency.  IDK, @wlcx r?

**Comment by LordAro** [comment]
/control/state/allowed vs /control/state/available

I would prefer available

**Comment by CaptainHayashi** [comment]
@LordAro ok, `available` it is

**Pull request merged**
